permalink: pretty
include: 
  - .cpanel.yml
author: Stan Overgauw
github:
  repository_url: https://github.com/stan2014/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
url: https://overgauw.com
title: Crazy ramblings