remote_theme: jekyll/minima
minima:
  skin: auto
  date_format: "%Y-%m-%d"
author:
  name: Stan Overgauw
  email: "stan (at) overgauw.com"
title: Personal blog
description: >
  Persoonlijke blog van Stan Overgauw
plugins:
  - jekyll-feed
