remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
name: Stan Overgauw
permalink: pretty
include: 
  - .cpanel.yml
show_downloads: false
author: Stan Overgauw
github:
  repository_url: https://github.com/stan2014/stan2014.github.io